cors:
  originPatterns: http://localhost:8080

security:
  jwt:
    jwtSecret: PMhFkVRvyY4XjLSENuf5edgq69Z7aJ
    jwtExpiration: 86400000

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://contact.cuuyz9uesp57.us-east-2.rds.amazonaws.com:5433/contact
    username: postgres
    password: postgres
  flyway:
    locations: classpath:db/migration
    enabled: true
    validate-on-migrate: true
    schemas: public

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: ./logs/log-file.log

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
